---
# Arduino Lint Configuration
# https://arduino.github.io/arduino-lint/latest/configuration/

# Project specific configuration
project:
  # Directories to exclude from linting
  exclude:
    - "libraries"
    - "ignore"

# Library specific configuration
library:
  # Disable library checks
  enabled: false

# Sketch specific configuration
sketch:
  # Enable sketch checks
  enabled: true
  # Disable specific sketch checks
  checks:
    # Disable include path checks
    IncludePaths: false 